basePath: /v1
definitions:
  main.GroupData:
    properties:
      invite_code:
        type: string
      name:
        type: string
    type: object
  main.GroupStatsPayload:
    properties:
      desired_date:
        example: "2026-03-17"
        type: string
      group_id:
        type: string
    required:
    - desired_date
    - group_id
    type: object
  main.KickUserPayload:
    properties:
      group_id:
        type: string
      user_to_kick_id:
        type: integer
    required:
    - group_id
    - user_to_kick_id
    type: object
  main.Notification:
    properties:
      body:
        type: string
      title:
        type: string
      to_user_id:
        type: integer
    required:
    - body
    - title
    - to_user_id
    type: object
  main.PresetNotification:
    properties:
      groupID:
        type: string
      messageId:
        format: int64
        type: integer
    type: object
  main.UserPayload:
    properties:
      device_id:
        maxLength: 255
        type: string
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 3
        type: string
      push_notification_token:
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - device_id
    - password
    - username
    type: object
  main.UserStatsPayload:
    properties:
      device_id:
        type: string
      recorded_at:
        example: "2026-03-17T12:00:00Z"
        type: string
      screen_time:
        type: integer
    required:
    - device_id
    - recorded_at
    - screen_time
    type: object
  storage.GroupStats:
    properties:
      email:
        type: string
      id:
        type: integer
      recorded_at:
        type: string
      screen_time:
        type: integer
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API powering ScreenScore backend system.
  title: ScreenScore Backend API
  version: "1.0"
paths:
  /groups/create/{groupName}:
    post:
      consumes:
      - application/json
      description: Creates a new group and returns invite code
      parameters:
      - description: Group name (URL parameter)
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.GroupData'
        "400":
          description: Group name malformed
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create new group
      tags:
      - groups
  /groups/join/{inviteCode}:
    post:
      consumes:
      - application/json
      description: Joins a group and returns group id
      parameters:
      - description: Invite code (URL parameter)
        in: path
        name: inviteCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Invite code malformed
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Join group
      tags:
      - groups
  /groups/kick:
    post:
      consumes:
      - application/json
      description: Anyone can kick another group member
      parameters:
      - description: Payload with user to kick and group id
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.KickUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "403":
          description: User with given id is not a member of the group
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Kick user
      tags:
      - groups
  /groups/leave/{groupId}:
    post:
      consumes:
      - application/json
      description: Leaves a group
      parameters:
      - description: Group id (URL parameter)
        in: path
        name: groupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Leave group
      tags:
      - groups
  /health:
    get:
      description: Checks if the server is active.
      responses:
        "200":
          description: OK
      summary: Health check
      tags:
      - utils
  /notifications/get_available_shop:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: List of messages
          schema:
            type: string
        "403":
          description: Forbidden access
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Retrives a list of all preset messages user can buy
      tags:
      - notifications
  /notifications/get_users_owned:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: List of messages
          schema:
            type: string
        "403":
          description: Forbidden access
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Retrives a list of all preset messages user owns
      tags:
      - notifications
  /notifications/purchase/{messageID}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Group id (URL parameter)
        in: path
        name: messageID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Purchased
          schema:
            type: string
        "400":
          description: Bad request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden access
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Purchase message from the shop
      tags:
      - notifications
  /notifications/send_custom:
    post:
      consumes:
      - application/json
      parameters:
      - description: Notification data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.Notification'
      produces:
      - application/json
      responses:
        "200":
          description: Sent
          schema:
            type: string
        "400":
          description: Bad request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Sends a custom notification to a user
      tags:
      - notifications
  /notifications/send_preset:
    post:
      consumes:
      - application/json
      parameters:
      - description: PresetNotification data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.PresetNotification'
      produces:
      - application/json
      responses:
        "200":
          description: Sent
          schema:
            type: string
        "400":
          description: Bad request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden access
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Sends preset notification to a group
      tags:
      - notifications
  /notifications/sendtestsilent/{token}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Token (URL parameter)
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Token malformed
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sends a test silent notification
      tags:
      - notifications
  /stats/get-group-stats:
    post:
      consumes:
      - application/json
      parameters:
      - description: Group stats payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.GroupStatsPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.GroupStats'
            type: array
        "400":
          description: Payload malformed
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: User with given id is not a member of the group
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Retrieves screentime data for all group memebers
      tags:
      - stats
  /stats/sync-stats:
    post:
      consumes:
      - application/json
      description: |-
        Updates or adds a new screen time record for a specific device.
        Includes logic to prevent "cheating" (time from future, screen time increasing faster than real time, etc.)
      parameters:
      - description: User screen time data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UserStatsPayload'
      produces:
      - application/json
      responses:
        "201":
          description: database updated
          schema:
            type: string
        "400":
          description: Validation error (Future time, time travel, invalid increments)
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Synchronize user screen time
      tags:
      - stats
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user, updates their device token, and returns a
        JWT.
      parameters:
      - description: Login credentials (username, password, device_id, push_token)
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - auth
  /users/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account, hashes the password, and links the
        initial device with a push token.
      parameters:
      - description: User registration data (email, username, password, device_id,
          push_token)
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            type: nil
        "400":
          description: User already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error during hashing or database insert
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
  /users/validate_token:
    post:
      consumes:
      - application/json
      description: Checks if jwt token is valid to skip login process
      produces:
      - application/json
      responses:
        "200":
          description: Valid token
          schema:
            type: string
        "401":
          description: Invalid token
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Validate JWT
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer <your-jwt-token>"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
